#!/usr/bin/env bash

# A list of bash command remaps and additional shortcuts I use to
# make my coding experience faster.
#
# Author: heavycircle
# Date: Sometime 2024
# License: MIT

# Bash config edits
alias bsrc='source ~/.bashrc'
alias bedit='$EDITOR ~/.bashrc'

# Color rebinds
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Flag rebinds
alias fzf='fzf --tmux'

# Shortcuts
alias e='exit'
alias c='clear'
alias cl='clear && ls'
alias nv='nvim $(fzf)'

# Simple functions
q() { mkdir '$1' && cd '$1'; }
