#!/usr/bin/env bash


# Color rebinds
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# Flag rebinds
alias fzf="fzf --tmux"

# Shortcuts
alias e="exit"
alias c="clear"
alias cl="clear && ls"
alias nv="nvim $(fzf)"

# Simple functions
q() { mkdir "$1" && cd "$1"; }
