#!/usr/bin/env bash

# Bash config edits
alias bsrc='source ~/.bashrc'
alias bedit='$EDITOR ~/.bashrc'

# # Rebind ls to eza
# alias ls='eza -l --group-directories-first --icons=auto'
# alias lsa='ls -a'
# alias lt='eza --tree --level=2 --long --icons --git'
# alias lta='lt -a'

# Color rebinds
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"

# Flag rebinds
alias fzf='fzf --tmux'
alias shfmt='shfmt -ci -i=4'

# Remaps
alias sl='ls'

# Shortcuts
alias e='exit'
alias c='clear'
alias cl='clear && ls'
alias r="ranger"
alias nv='nvim $(fzf)'
alias mkenv='uv venv --prompt "$(basename "$PWD")"'
alias venv='source .venv/bin/activate'

# Simple functions
q() { mkdir -p "$2" && cd "$1" || return $?; }
root() { cd "$(tmux display-message -p '#{session_path}')" || return $?; }
