#!/usr/bin/env bash

B="\[\033[1m\]"
RESET="\[\033[0m\]"

rgb() {
    local r=$(printf '%d' "0x$1")
    local g=$(printf '%d' "0x$2")
    local b=$(printf '%d' "0x$3")

    echo "\[\033[38;2;$r;$g;${b}m\]"
}

cwd() {
    echo -ne "$CWD_COLOR$B\w$RESET"
}

git-branch() {
    git rev-parse --is-inside-work-tree &>/dev/null || return
    local branch=$(git symbolic-ref --short HEAD 2>/dev/null)
    [[ -n "$branch" ]] || return

    echo -ne "$GIT_COLOR$B"
    echo -ne "[ $branch]"
    echo -ne "$RESET"
}

python-venv() {
    export VIRTUAL_ENV_DISABLE_PROMPT=1
    [[ -n "$VIRTUAL_ENV" ]] || return
    local venv=$(basename "$VIRTUAL_ENV_PROMPT")

    echo -ne "$VENV_COLOR$B"
    echo -ne "[ $venv]"
    echo -ne "$RESET"
}

last-exit() {
    local code="$1"
    ((code == 0)) && return

    echo -ne "\[\033[1;31m\]$B"
    echo -ne " $code"
    echo -ne "$RESET"
}

prompt-sign() {
    echo -ne "$FG_COLOR$B"
    echo -ne "\$ "
    echo -ne "$RESET"
}

make-prompt() {
    local code=$?

    source ~/.config/bash/theme.sh

    PS1="\n"
    PS1+="$(cwd) $(git-branch) $(python-venv) $(last-exit $code)\n"
    PS1+="$(prompt-sign)"
}

export PROMPT_COMMAND=make-prompt
